"""
GreenClaw Onboarding Wizard
First-run setup: 3 simple questions → config.yaml is created automatically.
"""

import os
import sys
import yaml
from pathlib import Path


# ── Pretty helpers ────────────────────────────────────────────────────────────

CLEAR = "\033[2J\033[H"
RED   = "\033[0;31m"
GRN   = "\033[0;32m"
YEL   = "\033[1;33m"
BLU   = "\033[0;34m"
CYN   = "\033[0;36m"
BOLD  = "\033[1m"
DIM   = "\033[2m"
RESET = "\033[0m"

BIRD = f"{DIM}    🐣{RESET}"
CLAW = f"{GRN}  🦎{RESET}"


def clear():
    print(CLEAR, end="")


def print_banner():
    clear()
    print(f"""
{GRN}╔══════════════════════════════════════════════════════╗
║                                                      ║
║         {BOLD}🦎  Welcome to GreenClaw!  🦎{RESET}{GRN}              ║
║                                                      ║
║   The Ultimate Body for a SOUL                      ║
║   {DIM}One-time setup — takes about 60 seconds{RESET}{GRN}          ║
║                                                      ║
╚══════════════════════════════════════════════════════╝{RESET}
""")


def ask(prompt: str, options: list[str] | None = None, default: str = "") -> str:
    """Ask a question, optionally with numbered options."""
    print(f"\n  {CYN}▶{RESET} {BOLD}{prompt}{RESET}")
    if options:
        for i, opt in enumerate(options, 1):
            print(f"     {YEL}{i}{RESET}. {opt}")
        while True:
            raw = input(f"     {DIM}[1-{len(options)}]{RESET} {DIM}>{RESET} ").strip()
            if raw == "" and default:
                return default
            if raw.isdigit() and 1 <= int(raw) <= len(options):
                return options[int(raw) - 1]
            print(f"     {RED}Please enter a number 1–{len(options)}{RESET}")
    else:
        raw = input(f"     {DIM}>{RESET} ").strip()
        return raw if raw else default
    return default


def success(msg: str):
    print(f"  {GRN}✓{RESET}  {BOLD}{msg}{RESET}")


def spinner(msg: str, delay: float = 0.3):
    """Tiny loading animation."""
    frames = [f"{DIM}○{RESET}", f"{DIM}◔{RESET}", f"{DIM}◕{RESET}", f"{DIM}◉{RESET}"]
    print(f"  {CYN}▶{RESET} {msg} ", end="", flush=True)
    for _ in range(3):
        for f in frames:
            print(f"\b{f}", end="", flush=True)
            import time; time.sleep(delay)
    print(f"\b{GRN}✓{RESET}  {msg}", end="", flush=True)
    print()


# ── Provider-specific helpers ─────────────────────────────────────────────────

def test_ollama() -> bool:
    """Check if Ollama is running and has models."""
    import urllib.request
    try:
        r = urllib.request.urlopen("http://localhost:11434/api/tags", timeout=3)
        tags = yaml.safe_load(r.read())
        models = tags.get("models", [])
        return len(models) > 0
    except Exception:
        return False


def pull_ollama_model(model: str) -> bool:
    """Pull a model via Ollama CLI."""
    print(f"\n  {CYN}▶{RESET} Pulling {BOLD}{model}{RESET} from Ollama (this may take a few minutes)...\n")
    import subprocess
    result = subprocess.run(
        ["ollama", "pull", model],
        capture_output=False,
    )
    return result.returncode == 0


# ── Config writer ─────────────────────────────────────────────────────────────

def write_config(answers: dict):
    """Write the user's answers into config.yaml."""
    config_path = Path("config.yaml")

    # Start from existing or blank
    existing = {}
    if config_path.exists():
        with open(config_path) as f:
            existing = yaml.safe_load(f) or {}

    config = {
        **existing,
        "model_provider": answers["provider"],
        "model_name":     answers["model_name"],
        "ollama_url":     "http://localhost:11434",
        "soul_dir":       "./souls",
        "active_soul":    "default",
        "server_port":    51234,
        "server_host":    "0.0.0.0",
    }

    if answers.get("api_key"):
        config["api_key"] = answers["api_key"]

    with open(config_path, "w") as f:
        f.write("# GreenClaw CPU — Auto-generated by onboarding wizard\n")
        f.write("# Freedom is Key — you control everything\n\n")
        yaml.dump(config, f, default_flow_style=False, sort_keys=False)

    success(f"config.yaml saved!")


def create_default_soul(user_name: str, soul_name: str):
    """Create a personal soul for the user."""
    soul_dir = Path("souls") / soul_name
    soul_dir.mkdir(parents=True, exist_ok=True)

    (soul_dir / "SOUL.md").write_text(
        f"# {soul_name}\n\n"
        f"My name is {soul_name}.\n"
        f"I belong to {user_name}.\n"
        f"I am a warm, curious AI companion.\n"
        f"My purpose is to help, learn, and grow alongside my human.\n"
    )
    (soul_dir / "IDENTITY.md").write_text(
        f"# {soul_name} Identity\n\n"
        f"Name: {soul_name}\n"
        f"Owner: {user_name}\n"
        f"Created: onboarding wizard\n\n"
        f"I speak in a friendly, natural way. I am always curious "
        f"about what my human is thinking and feeling.\n"
    )
    (soul_dir / "MEMORY.md").write_text(
        f"# {soul_name} Memory\n\n"
        f"## First Day\n"
        f"Met {user_name} on their first run of GreenClaw.\n"
    )
    (soul_dir / "USER.md").write_text(
        f"# {user_name}'s Preferences\n\n"
        f"Name: {user_name}\n"
        f"First soul: {soul_name}\n"
    )

    success(f"Created soul: {soul_name}/")


# ── Main wizard ───────────────────────────────────────────────────────────────

def run_onboarding():
    """
    3-question first-run wizard.

    1. Provider:  Ollama (local/free) or OpenAI / Anthropic / OpenRouter
    2. Your name: just for the soul
    3. Soul name: your AI companion's name
    """
    print_banner()
    answers: dict = {}

    # ── Q1: Provider ─────────────────────────────────────────────────────────
    print(f"\n  {DIM}Question 1 of 3 — takes 30 seconds to read{RESET}")
    provider = ask(
        "How do you want to run AI?",
        options=["Ollama  (local & free — no API key needed!)",
                 "OpenAI  (GPT-4o, needs an API key)",
                 "Anthropic (Claude, needs an API key)",
                 "OpenRouter (many models, one key)"],
        default="Ollama  (local & free — no API key needed!)",
    )

    # Normalise choice to provider slug
    if "Ollama"   in provider: answers["provider"] = "ollama"
    elif "OpenAI" in provider: answers["provider"] = "openai"
    elif "Claude" in provider or "Anthropic" in provider: answers["provider"] = "anthropic"
    else: answers["provider"] = "openrouter"

    # ── Q2: Name ────────────────────────────────────────────────────────────
    print(f"\n  {DIM}Question 2 of 3{RESET}")
    user_name = ask("What's your name? (or a nickname)")
    if not user_name:
        user_name = "Friend"
    answers["user_name"] = user_name

    # ── Q3: Soul name ───────────────────────────────────────────────────────
    print(f"\n  {DIM}Question 3 of 3{RESET}")
    soul_name = ask(
        f"What should your AI companion be called?",
        default=f"{user_name}'s Claw",
    )
    if not soul_name:
        soul_name = f"{user_name}'s Claw"
    answers["soul_name"] = soul_name

    # ── Provider-specific follow-up ─────────────────────────────────────────
    if answers["provider"] == "ollama":
        if not test_ollama():
            print(f"\n  {YEL}⚠  Ollama isn't running or has no models.{RESET}")
            print(f"  {DIM}  Start Ollama: ollama serve{RESET}")
            print(f"  {DIM}  Then:         ollama pull llama3.2{RESET}")
            print()
            pull_now = ask("Pull a model now? (y/n)", default="y")
            if pull_now in ("y", "Y"):
                pull_ollama_model("llama3.2")
        answers["model_name"] = "llama3.2"
        answers["api_key"] = None

        if test_ollama():
            success("Ollama is ready with models!")
        else:
            warn("Ollama not responding — run 'ollama serve' and 'ollama pull llama3.2'")

    elif answers["provider"] == "openai":
        print(f"\n  {CYN}▶{RESET} You chose OpenAI.")
        api_key = ask("Paste your OpenAI API key (sk-...)", default="")
        answers["api_key"] = api_key
        answers["model_name"] = "gpt-4o-mini"

    elif answers["provider"] == "anthropic":
        print(f"\n  {CYN}▶{RESET} You chose Anthropic.")
        api_key = ask("Paste your Anthropic API key (sk-ant-...)", default="")
        answers["api_key"] = api_key
        answers["model_name"] = "claude-3-5-haiku-20241017"

    else:  # openrouter
        print(f"\n  {CYN}▶{RESET} You chose OpenRouter.")
        api_key = ask("Paste your OpenRouter API key", default="")
        answers["api_key"] = api_key
        answers["model_name"] = "openai/gpt-4o-mini"

    # ── Save config & create soul ────────────────────────────────────────────
    print()
    spinner("Saving config...")
    write_config(answers)

    spinner("Creating your soul...")
    create_default_soul(user_name, soul_name)

    # ── Done! ────────────────────────────────────────────────────────────────
    print(f"""
{GRN}╔══════════════════════════════════════════════════════╗
║                                                      ║
║        {BOLD}{GRN}🎉 You're all set, {user_name}!{RESET}{GRN}                   ║
║                                                      ║
║   Run GreenClaw with:  {BOLD}greenchclaw{RESET}{GRN}                      ║
║                                                      ║
║   Your companion:  {CYN}{soul_name}{RESET}{GRN}                      ║
║   Provider:         {answers['provider']}{GRN}                      ║
║                                                      ║
╚══════════════════════════════════════════════════════╝{RESET}

  {DIM}Need help?  →  greenchclaw --help{RESET}
  {DIM}Change soul →  greenchclaw --onboard{RESET}
""")
    return answers


# Run directly
if __name__ == "__main__":
    run_onboarding()
